-- MySQL Script generated by MySQL Workbench
-- Sun Apr  9 22:09:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `cep` INT(8) NOT NULL,
  `logradouro` VARCHAR(50) NULL,
  `bairro` VARCHAR(15) NULL,
  `uf` VARCHAR(2) NULL,
  PRIMARY KEY (`cep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`colaborador` (
  `cpf` VARCHAR(12) NOT NULL,
  `rg` VARCHAR(12) NOT NULL,
  `nome_completo` VARCHAR(50) NOT NULL,
  `telefone_celular` VARCHAR(25) NULL,
  `telefone_fixo` VARCHAR(25) NULL,
  `email` VARCHAR(40) NULL,
  `numero_endereco` VARCHAR(10) NULL,
  `acesso_sistema` VARCHAR(8) NULL,
  `nacionalidade` VARCHAR(10) NULL,
  `data_de_nascimento` DATE NULL,
  `senha` VARCHAR(8) NOT NULL,
  `endereco_cep` INT(8) NOT NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_colaborador_endereco1_idx` (`endereco_cep` ASC),
  CONSTRAINT `fk_colaborador_endereco1`
    FOREIGN KEY (`endereco_cep`)
    REFERENCES `mydb`.`endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `cnpj_cliente` CHAR(14) NOT NULL,
  `nome_fantasia` VARCHAR(40) NULL,
  `razao_social` VARCHAR(40) NOT NULL,
  `numero_endereco` VARCHAR(10) NULL,
  `primeiro_contato` DATE NULL,
  `etapa_venda` VARCHAR(10) NOT NULL,
  `colaborador_cpf` VARCHAR(12) NOT NULL,
  `endereco_cep` INT(8) NOT NULL,
  PRIMARY KEY (`cnpj_cliente`, `colaborador_cpf`),
  INDEX `fk_cliente_colaborador1_idx` (`colaborador_cpf` ASC),
  INDEX `fk_cliente_endereco1_idx` (`endereco_cep` ASC),
  CONSTRAINT `fk_cliente_colaborador1`
    FOREIGN KEY (`colaborador_cpf`)
    REFERENCES `mydb`.`colaborador` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_endereco1`
    FOREIGN KEY (`endereco_cep`)
    REFERENCES `mydb`.`endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pergunta_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pergunta_cliente` (
  `id_pergunta` INT(15) NOT NULL,
  `pergunta1` VARCHAR(60) NULL,
  `resposta1` VARCHAR(60) NULL,
  `cliente_cnpj_cliente` CHAR(14) NOT NULL,
  PRIMARY KEY (`id_pergunta`),
  INDEX `fk_Pergunta_cliente_cliente1_idx` (`cliente_cnpj_cliente` ASC),
  CONSTRAINT `fk_Pergunta_cliente_cliente1`
    FOREIGN KEY (`cliente_cnpj_cliente`)
    REFERENCES `mydb`.`cliente` (`cnpj_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`associado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`associado` (
  `cnpj_associado` CHAR(14) NOT NULL,
  `nome_fantasia` VARCHAR(60) NULL,
  `razao_social` VARCHAR(60) NULL,
  `numero_endereco` VARCHAR(10) NULL,
  `endereco_cep` INT(8) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  `telefone_fixo` VARCHAR(45) NULL,
  `telefone_celular` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `site` VARCHAR(45) NULL,
  `tipo_produto` VARCHAR(15) NULL,
  `tipo_venda` VARCHAR(10) NULL,
  `observacao` VARCHAR(70) NULL,
  PRIMARY KEY (`cnpj_associado`, `endereco_cep`),
  INDEX `fk_associado_endereco_idx` (`endereco_cep` ASC),
  CONSTRAINT `fk_associado_endereco`
    FOREIGN KEY (`endereco_cep`)
    REFERENCES `mydb`.`endereco` (`cep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `id_produto` INT(10) NOT NULL,
  `descricao` VARCHAR(40) NULL,
  `preco_unitario` INT(8) NULL,
  `associado_cnpj_associado` CHAR(14) NOT NULL,
  INDEX `fk_produto_associado1_idx` (`associado_cnpj_associado` ASC),
  PRIMARY KEY (`id_produto`),
  CONSTRAINT `fk_produto_associado1`
    FOREIGN KEY (`associado_cnpj_associado`)
    REFERENCES `mydb`.`associado` (`cnpj_associado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compra` (
  `produto_id_produto` INT(10) NOT NULL,
  `cliente_cnpj_cliente` CHAR(14) NOT NULL,
  `quantidade` INT(4) NULL,
  `data` DATE NULL,
  `forma de pagamento` VARCHAR(10) NULL,
  `situacao_pagamento` VARCHAR(15) NULL,
  PRIMARY KEY (`produto_id_produto`, `cliente_cnpj_cliente`),
  INDEX `fk_produto_has_cliente_cliente1_idx` (`cliente_cnpj_cliente` ASC),
  INDEX `fk_produto_has_cliente_produto1_idx` (`produto_id_produto` ASC),
  CONSTRAINT `fk_produto_has_cliente_produto1`
    FOREIGN KEY (`produto_id_produto`)
    REFERENCES `mydb`.`produto` (`id_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_cliente_cliente1`
    FOREIGN KEY (`cliente_cnpj_cliente`)
    REFERENCES `mydb`.`cliente` (`cnpj_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contato_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contato_cliente` (
  `id_contato` INT(8) NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(40) NULL,
  `cargo` VARCHAR(15) NULL,
  `email` VARCHAR(40) NULL,
  `telefone_fixo` VARCHAR(20) NULL,
  `telefone_celular` VARCHAR(20) NULL,
  `cliente_cnpj_cliente` CHAR(14) NOT NULL,
  PRIMARY KEY (`id_contato`),
  INDEX `fk_contato_cliente_cliente1_idx` (`cliente_cnpj_cliente` ASC),
  CONSTRAINT `fk_contato_cliente_cliente1`
    FOREIGN KEY (`cliente_cnpj_cliente`)
    REFERENCES `mydb`.`cliente` (`cnpj_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
